### ISSUE TITLE
1.18.2 crash after migrating from offline player into online player with simpler auth mod

### ISSUE THREAD

**Issue by DadoIrie** [CleverNucleus/Offline-Player-Cache#1]
hope the title says everything

basically the first time the player logs in the player is in offline mode and when switching into online mode with the /onlineauth command and when this player logs out this message pop up on the servers console and server crashes
![image](https://user-images.githubusercontent.com/61109153/186140201-34e08fde-bd8d-47cd-accc-f8bd04f4ab0b.png)
[SimplerAuth Github](https://github.com/Additional-Mods/simplerauth) in case needing to look into the source code

EDIT: most likely because the uuid gets changed from offline mode uuid to online official uuid, but the player name is still the same?

**Comment by CleverNucleus** [comment]
Hi there,
Thank you for bringing this to my attention - you're reasoning is essentially correct, I'll work on releasing a fix soon.

**Comment by DadoIrie** [comment]
awesome ... 

disabled OPC until its fixed, but still happens - then I saw that it is bundled into playerex :) hope playerex's opc gets updated aswell

EDIT: meanwhile which file do I need to delete instead of the whole world folder? (re-post edit)

**Comment by CleverNucleus** [comment]
Yeah OPC is bundled with PlayerEx, so you cannot disable it without disabling PlayerEx.

You need a nbt editor (such as NBT Explorer) and navigate to your world file/level.dat. Inside you can delete the OfflinePlayerCache tag.

**Comment by DadoIrie** [comment]
omg ... thanks, but nah .. I'll wait patiently for the fix :)

**Comment by DadoIrie** [comment]
but if editing this with the nbt editor will a new opc tag get generated?

EDIT: my bad ... just tested this out and yes it does get generated and fixes the crash ... still fix will be needed as this is not a optimal workaround :)

**Comment by CleverNucleus** [comment]
Releases of PlayerEx for 1.18.2, 1.19 and 1.19.2 bundled with fixed versions of OPC are now available on Modrinth, pending Curseforge and Github. This crash *should* no longer occur.
